---
# tasks file for qemu

- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags: qemu

- include: CentOS.yml
  when: ansible_distribution == "CentOS"
  tags: qemu

- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags: qemu
