---
# tasks file for qemu (Ubuntu specific)

- name: Install QEMU packages
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "{{ qemu_packages }}"
  tags:
    - qemu
